// Generated by CoffeeScript 1.10.0
var editor;

editor = CodeMirror($('#code').get(0), {
  lineNumbers: true,
  mode: "javascript",
  keyMap: "sublime",
  autoCloseBrackets: true,
  matchBrackets: true,
  showCursorWhenSelecting: true,
  theme: "monokai",
  tabSize: 4,
  indentUnit: 4,
  indentWithTabs: true
});

exports.openCode = function(code) {
  editor.value = code;
  $('#code').removeClass('hidden');
  return editor.refresh();
};

exports.closeCode = function() {
  return $('#code').addClass('hidden');
};
