// Generated by CoffeeScript 1.7.1
(function() {
  var activeTab, nodes, nodesTab, subjects, subjectsTab, toggle, trees, treesTab;

  treesTab = $('#tab-trees');

  nodesTab = $('#tab-nodes');

  subjectsTab = $('#tab-subjects');

  trees = $('#trees');

  nodes = $('#nodes');

  subjects = $('#nodes');

  activeTab = nodes;

  toggle = function() {
    var tab;
    if (activeTab.attr('id') === $(this).attr('id')) {
      return;
    }
    activeTab = $(this);
    $(this).toggleClass('active');
    $(this).siblings().removeClass('active');
    tab = $(this).attr('data');
    $('.panelContent').not(tab).css('display', 'none');
    return $(tab).show();
  };

  treesTab.on('click', toggle);

  nodesTab.on('click', toggle);

  subjectsTab.on('click', toggle);

}).call(this);
